title: Pascamel
email: nope@gmail.com
description: Matrix was huge in 1999
baseurl: ''
url: ''
github: pascamel
statement: Move fast, break things
# Build settings
# theme: minima
plugins:
  - jekyll-feed

assets_path: '/assets' # i.e. "/assets"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
bgtext: 'αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√'
